# dbt_project.yml
name: 'proyecto_dbt'
version: '1.0.0'
config-version: 2

profile: 'mi_db_profile' # Debe coincidir con el nombre en profiles.yml

model-paths: ["models"] #model-paths le dice a dbt dónde están tus archivos de código .sql (tus scripts de staging, hechos y dimensiones)

on-run-start:
  - "INSTALL delta;"
  - "LOAD delta;"

models:
  proyecto_dbt:
    # Por defecto, todo en staging serán VISTAS en DuckDB (no duplica datos)
    staging:
      +materialized: view
    # Todo lo que esté en marts se guardará como TABLAS físicas
    marts:
      # Tuve que poner formato tabla/incremental para que dbt gestione los duplicados
      # porque dbt no es bueno para escribir delta sin un plugin
      +materialized: incremental
      +incremental_strategy: merge  # <-- ¡MERGE!
      +unique_key: 'repo_name'       # La clave primaria para evitar duplicados

vars:
  ruta_delta_bruto: "C:/010_/Trends-Watcher/output/bronze/delta_bruto"
