# Aquí es donde sí va la ruta de tu Delta bruto. 
# Porque para tener una Capa Silver, hay que tener una fuente,
#y Esa fuente es a la que apunta el .sql de models/staing/delta_silver.sql
#que va a crear la View o Espejo FIEL de los datos Bronce generados
# por spark
#Le dices a dbt: "Oye, usando el motor que configuré en el profile (DuckDB), 
# ve a buscar datos externos a esta carpeta de Spark".
#Es decir, estás registrando el "Delta Bruto" como Fuente (Sources)
#Este archivo no ejecuta código, solo le dice a dbt: 
# "Oye, en esta ruta del disco hay datos crudos que dejó Spark

# models/delta_bronze/sources.yml
version: 2

sources:
  - name: delta_spark
    meta:
      plugin: delta
    description: "Datos transformados y generados por Spark en formato Delta"
    tables:
      - name: trends
        external_location: "C:/010_/Trends-Watcher/output/bronze/delta_bruto"